kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  labels:
{{ include "mssql.labels" . | indent 4 }}
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.capacity}}
