apiVersion: v1
kind: Service
metadata:
  name : {{ include "mssql.fullname" . }}
  labels:
{{ include "mssql.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "mssql.fullname" . }}
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433