kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: azure-disk
  labels:
{{ include "mssql.labels" . | indent 4 }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
